#! /usr/bin/env python

import sys
from avro import schema
from avro.genericio import DatumReader
from avro.io import DataFileReader

if __name__ == "__main__":
  if len(sys.argv) < 2:
    print "Need to at least specify an Avro file."
  outfile_name = sys.argv[1]

  message_schema = None
  if len(sys.argv) > 2:
    message_schema = schema.parse(schema.parse(sys.argv[2].encode("utf-8")))

  r = file(outfile_name, 'r')
  dr = DatumReader(expected = message_schema)
  dfr = DataFileReader(r, dr)
  for record in dfr:
    print record
  dfr.close()
