#! /usr/bin/env python
import sys
from avro import new_schema as schema

if __name__ == '__main__':
  for i, schema_to_test in enumerate(sys.argv[1:]):
    schema_object = schema.parse(schema_to_test)
    parsed = True

    schema_as_str = str(schema_object)
    round_trip_schema_object = schema.parse(schema_as_str)
    parse_and_print = True
    
    round_trip = schema_object == round_trip_schema_object

    # print results
    print 'Test Schema #%d' % i
    print '==============='
    print 'Schema: %s' % schema_to_test
    print ''
    print 'Parsed Correctly: %s' % parsed
    print 'Print as String: %s' % parse_and_print
    print 'Round Trip: %s' % round_trip
    print ''