#! /usr/bin/env python

import sys

if __name__ == "__main__":
  for file_name in sys.argv[1:]:
    infile = open(file_name, 'r')
    lines = infile.readlines()
    infile.close()

    header_comment = True
    for i, line in enumerate(lines):
      if not header_comment:
        lines[i] = line
      elif line.startswith('# '):
        lines[i] = line
      elif line.startswith('#!'):
        lines[i] = line
      elif line.startswith('#'):
        lines[i] = line[0] + ' ' + line[1:]
      else:
        header_comment = False

    outfile = open(file_name, 'w')
    outfile.write(''.join(lines))
    outfile.close()
