#! /usr/bin/env python
from simplejson import loads
from pprint import pprint
from cStringIO import StringIO

# if you want to verify that the pprint'ed schema
# matches the ugly schema, stick the pprint'ed schema here.
# otherwise, a pprint'ed schema will be written to stdout.
schema_pprint = """\
"""

# stick ugly schema here
schema_ugly = """\
"""

def pprint_schema(schema_ugly):
  str_buff = StringIO()
  pprint(loads(schema_ugly), str_buff)
  str_buff.seek(0)
  str_with_single_quotes = str_buff.read()
  return str_with_single_quotes.replace("'", '"')

if __name__ == "__main__":
  if not schema_pprint: schema_pprint = pprint_schema(schema_ugly)
  print loads(schema_pprint) == loads(schema_ugly)
  print schema_pprint

